# config/database.yml

default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  primary:
    <<: *default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>